services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      # TODO: consider adding a `condition: healthy` check with healthcheck `psql $DATABASE_URL -c '\l'`
      - db
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./:/app
  db:
    image: postgres:14-alpine
    restart: "on-failure"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
