# Generated by Django 4.1.2 on 2022-11-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "party",
                    models.CharField(
                        choices=[
                            ("C", "Constitution"),
                            ("D", "Democrat"),
                            ("G", "Pacific Green"),
                            ("I", "Independent"),
                            ("L", "Libertarian"),
                            ("N", "No party"),
                            ("O", "Other"),
                            ("P", "Progressive"),
                            ("R", "Republican"),
                            ("U", "Unknown"),
                            ("W", "Working Families Party"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
