# Generated by Django 4.1.2 on 2022-11-03 19:48

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("first_name"),
                django.db.models.functions.text.Lower("last_name"),
                models.F("date_of_birth"),
                name="candidate_unique_first_last_dob",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("first_name"),
                django.db.models.functions.text.Lower("last_name"),
                condition=models.Q(("date_of_birth__isnull", True)),
                name="candidate_unique_first_last_null_dob",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("first_name"),
                models.F("date_of_birth"),
                condition=models.Q(("last_name__isnull", True)),
                name="candidate_unique_first_dob_null_last",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("first_name"),
                condition=models.Q(
                    ("date_of_birth__isnull", True), ("last_name__isnull", True)
                ),
                name="candidate_unique_first_null_dob_last",
            ),
        ),
    ]
