# Generated by Django 4.1.2 on 2022-11-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_candidate_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="middle_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
