# Generated by Django 4.1.2 on 2022-11-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_candidate_middle_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endorser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("abbreviation", models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
