# Generated by Django 4.1.3 on 2022-11-25 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_candidate_candidate_unique_first_dob_null_last_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatEndorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("election_date", models.DateField()),
                ("url", models.URLField(max_length=500)),
                ("candidates", models.ManyToManyField(to="api.candidate")),
                (
                    "endorser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.endorser"
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.seat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeasureEndorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("election_date", models.DateField()),
                ("url", models.URLField(max_length=500)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                        max_length=1,
                    ),
                ),
                (
                    "endorser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.endorser"
                    ),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.measure"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="seatendorsement",
            constraint=models.UniqueConstraint(
                models.F("endorser"),
                models.F("election_date"),
                models.F("seat"),
                name="seat_endorsement_unique_endorser_election_date_seat",
            ),
        ),
        migrations.AddConstraint(
            model_name="measureendorsement",
            constraint=models.UniqueConstraint(
                models.F("endorser"),
                models.F("election_date"),
                models.F("measure"),
                name="measure_endorsement_unique_endorser_election_date_measure",
            ),
        ),
    ]
