# Generated by Django 4.1.4 on 2022-12-25 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_seatendorsement_measureendorsement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="running_for_seat",
            field=models.ForeignKey(
                blank=True,
                help_text="The seat a candidate is running for.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.seat",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                help_text="The seat a candidate is currently holding (if any).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incumbent",
                to="api.seat",
            ),
        ),
    ]
